dbfilename redis_queue.rdb
dir /home/sanskaar/Devlop/dev/config/pids
pidfile /home/sanskaar/Devlop/dev/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/sanskaar/Devlop/dev/config/redis_queue.acl
